apiVersion: v2
name: karpenter
description: Helm chart for installing Karpenter on Amazon EKS cluster
type: application
version: 0.0.1
appVersion: 1.0.0
dependencies:
  - name: karpenter
    version: v0.22.1
    repository: oci://public.ecr.aws/karpenter