karpenter:
  serviceAccount:
    create: false
  nodeSelector:
    karpenter.io/os: linux
  settings:
    aws:
      clusterName:
      clusterEndpoint:
      defaultInstanceProfile:
      interruptionQueueName: