server:
  service:
    statefulSetReplica:
      enabled: true
      replica: 3
  replicaCount: 3
  statefulSet:
    enabled: true
  retention: "7d"
  resources:
    requests:
      cpu: 1024m
      memory: 2048Mi
  global:
    scrape_interval: 15
