apiVersion: v2
name: external-secrets
description: Helm chart for installing External Secrets Operator (ESO)
type: application
version: 0.0.1
appVersion: "1.0.0"
dependencies:
  - name: external-secrets
    version: 0.8.3
    repository: https://charts.external-secrets.io/